### ISSUE TITLE
Exception when trying to change server url before signup

### ISSUE THREAD

**Issue by Excape** [raphiz/gadgeothek#27]
Steps to reproduce:

1. Click on Signup
2. Change server url (e.g. from mge1 to mge2)
3. enter details and click signup

Tracelog:
```
10-31 19:11:05.958 5268-5564/ch.hsr.gadgeothek D/Request: Requesting http://mge2.dev.ifs.hsr.ch/public/register
10-31 19:11:06.366 5268-5564/ch.hsr.gadgeothek D/Request: Response received: true
10-31 19:11:06.397 5268-5268/ch.hsr.gadgeothek D/LibraryService: Setting server to http://mge3.dev.ifs.hsr.ch/public
10-31 19:11:06.398 5268-5575/ch.hsr.gadgeothek D/Request: Requesting http://mge3.dev.ifs.hsr.ch/public/login
10-31 19:11:06.450 5268-5575/ch.hsr.gadgeothek D/Request: Response received: "user does not exist"
10-31 19:11:06.515 5268-5268/ch.hsr.gadgeothek D/AndroidRuntime: Shutting down VM
10-31 19:11:06.516 5268-5268/ch.hsr.gadgeothek E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: ch.hsr.gadgeothek, PID: 5268
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.view.ViewGroup.getContext()' on a null object reference
                                                                     at android.support.design.widget.Snackbar.<init>(Snackbar.java:188)
                                                                     at android.support.design.widget.Snackbar.make(Snackbar.java:220)
                                                                     at ch.hsr.gadgeothek.util.ErrorHandler.showOverallErrorMsg(ErrorHandler.java:11)
                                                                     at ch.hsr.gadgeothek.ui.SignupActivity$1$1.onError(SignupActivity.java:42)
                                                                     at ch.hsr.gadgeothek.service.LibraryService$1.onError(LibraryService.java:69)
                                                                     at ch.hsr.gadgeothek.service.Request.onPostExecute(Request.java:97)
                                                                     at ch.hsr.gadgeothek.service.Request.onPostExecute(Request.java:17)
                                                                     at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                     at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by jmatj** [comment]
Bug lässt sich auf meinem Gerät und im Emulator leider nicht reproduzieren.

**Comment by jmatj** [comment]
@raphiz kannst du das reproduzieren?
